// Default permission configuration and mappings

import { PERMISSION_RESOURCES, PERMISSION_ACTIONS } from './permission.types';

// Default permissions for each role
export const DEFAULT_ROLE_PERMISSIONS = {
  teacher: [
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.SUBMIT}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.MILESTONE}.${PERMISSION_ACTIONS.READ}`,
  ],
  assistant_director: [
    // All teacher permissions plus...
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.SUBMIT}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.APPROVE}`,
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.REJECT}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.DELETE}`,
    `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.MILESTONE}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.MILESTONE}.${PERMISSION_ACTIONS.CREATE}`,
  ],
  director: [
    // All assistant director permissions plus...
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.MILESTONE}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.ROOM}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.LOCATION}.${PERMISSION_ACTIONS.READ}`,
  ],
  admin: [
    // Full permissions for their locations
    `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.MILESTONE}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.SETTINGS}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.LOCATION}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.ROOM}.${PERMISSION_ACTIONS.MANAGE}`,
  ],
  superadmin: [
    // Complete system access
    '*.*', // Wildcard for all permissions
  ],
};

// Default approval requirements by role
export const DEFAULT_APPROVAL_REQUIREMENTS = {
  lesson_plan_submit: {
    requiresApproval: ['teacher'], // Roles that need approval
    autoApprove: ['assistant_director', 'director', 'admin', 'superadmin'], // Roles that auto-approve
  },
};

// All available permissions in the system
export const SYSTEM_PERMISSIONS = [
  // Lesson Plan permissions
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.CREATE}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.CREATE,
    description: 'Create new lesson plans',
  },
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.READ}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.READ,
    description: 'View lesson plans',
  },
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.UPDATE}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.UPDATE,
    description: 'Edit existing lesson plans',
  },
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.DELETE}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.DELETE,
    description: 'Delete lesson plans',
  },
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.SUBMIT}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.SUBMIT,
    description: 'Submit lesson plans for review',
  },
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.APPROVE}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.APPROVE,
    description: 'Approve submitted lesson plans',
  },
  {
    name: `${PERMISSION_RESOURCES.LESSON_PLAN}.${PERMISSION_ACTIONS.REJECT}`,
    resource: PERMISSION_RESOURCES.LESSON_PLAN,
    action: PERMISSION_ACTIONS.REJECT,
    description: 'Reject submitted lesson plans',
  },
  // Activity permissions
  {
    name: `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.CREATE}`,
    resource: PERMISSION_RESOURCES.ACTIVITY,
    action: PERMISSION_ACTIONS.CREATE,
    description: 'Create new activities',
  },
  {
    name: `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.READ}`,
    resource: PERMISSION_RESOURCES.ACTIVITY,
    action: PERMISSION_ACTIONS.READ,
    description: 'View activities',
  },
  {
    name: `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.UPDATE}`,
    resource: PERMISSION_RESOURCES.ACTIVITY,
    action: PERMISSION_ACTIONS.UPDATE,
    description: 'Edit existing activities',
  },
  {
    name: `${PERMISSION_RESOURCES.ACTIVITY}.${PERMISSION_ACTIONS.DELETE}`,
    resource: PERMISSION_RESOURCES.ACTIVITY,
    action: PERMISSION_ACTIONS.DELETE,
    description: 'Delete activities',
  },
  // Material permissions
  {
    name: `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.CREATE}`,
    resource: PERMISSION_RESOURCES.MATERIAL,
    action: PERMISSION_ACTIONS.CREATE,
    description: 'Create new materials',
  },
  {
    name: `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.READ}`,
    resource: PERMISSION_RESOURCES.MATERIAL,
    action: PERMISSION_ACTIONS.READ,
    description: 'View materials',
  },
  {
    name: `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.UPDATE}`,
    resource: PERMISSION_RESOURCES.MATERIAL,
    action: PERMISSION_ACTIONS.UPDATE,
    description: 'Edit existing materials',
  },
  {
    name: `${PERMISSION_RESOURCES.MATERIAL}.${PERMISSION_ACTIONS.DELETE}`,
    resource: PERMISSION_RESOURCES.MATERIAL,
    action: PERMISSION_ACTIONS.DELETE,
    description: 'Delete materials',
  },
  // Settings permissions
  {
    name: `${PERMISSION_RESOURCES.SETTINGS}.${PERMISSION_ACTIONS.MANAGE}`,
    resource: PERMISSION_RESOURCES.SETTINGS,
    action: PERMISSION_ACTIONS.MANAGE,
    description: 'Manage organization settings',
  },
  // User permissions
  {
    name: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.MANAGE}`,
    resource: PERMISSION_RESOURCES.USER,
    action: PERMISSION_ACTIONS.MANAGE,
    description: 'Manage users and roles',
  },
];